### PR TITLE
iomgr and pnpmgr refactoring

### PR DESCRIPTION
**Pull request by MasonLeeBack**

### CODE REVIEW

**Comment by MasonLeeBack** [comment]
There are a few bugfixes that I need to make, so wait before merging.

**Comment by MasonLeeBack** [comment]
Some work needs done before I can send a full pull request, unfortunately I am unable to do that tonight.

**Comment by stephanosio** [comment]
I will try to look into it over the weekend. I'm currently busy with work stuff at the moment.

**Comment by MasonLeeBack** [comment]
I tested the branch in qemu and it seems to work fine. Virtualbox was just causing me some problems.

**Pull request merged**
